"""Added new tables: Item, Lesson, Lesson_type, Stats

Revision ID: 4b973c40c22f
Revises: 27611acf17ef
Create Date: 2024-05-01 20:09:46.285017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b973c40c22f'
down_revision: Union[str, None] = '27611acf17ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('lesson_type',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('lesson',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('lesson_type', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('reward', sa.Integer(), nullable=False),
    sa.Column('path', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['lesson_type'], ['lesson_type.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('lesson_id', sa.BigInteger(), nullable=False),
    sa.Column('earned_points', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('part_of_speech_words')
    op.drop_table('part_of_speech')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part_of_speech',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('part_of_speech_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('part', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='part_of_speech_pkey'),
    sa.UniqueConstraint('id', name='part_of_speech_id_key'),
    sa.UniqueConstraint('part', name='part_of_speech_part_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('part_of_speech_words',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('word', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('part_of_speech_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['part_of_speech_id'], ['part_of_speech.id'], name='part_of_speech_words_part_of_speech_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='part_of_speech_words_pkey'),
    sa.UniqueConstraint('id', name='part_of_speech_words_id_key'),
    sa.UniqueConstraint('word', name='part_of_speech_words_word_key')
    )
    op.drop_table('stats')
    op.drop_table('lesson')
    op.drop_table('lesson_type')
    op.drop_table('item')
    # ### end Alembic commands ###
