"""Initial revision

Revision ID: 55fb9694dd6d
Revises: 
Create Date: 2024-03-16 00:20:12.807300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55fb9694dd6d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('country', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country'),
    sa.UniqueConstraint('id')
    )
    op.create_table('part_of_speech',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('part', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('part')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.BigInteger(), nullable=True),
    sa.Column('register_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('login', sa.VARCHAR(length=255), nullable=False),
    sa.Column('hashed_password', sa.CHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('classroom',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('owner', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('owner')
    )
    op.create_table('part_of_speech_words',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('word', sa.VARCHAR(length=100), nullable=False),
    sa.Column('part_of_speech_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['part_of_speech_id'], ['part_of_speech.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('word')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('part_of_speech_words')
    op.drop_table('classroom')
    op.drop_table('user')
    op.drop_table('part_of_speech')
    op.drop_table('country')
    # ### end Alembic commands ###
