"""Removed path column from Lesson table

Revision ID: 607bd795d11f
Revises: f50b9bcf6db8
Create Date: 2024-05-02 16:36:40.608667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '607bd795d11f'
down_revision: Union[str, None] = 'f50b9bcf6db8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('path', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
