"""Added autoincrement for tables

Revision ID: 8345427704ff
Revises: 9a0cc07bc832
Create Date: 2024-03-05 22:36:43.433391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8345427704ff'
down_revision: Union[str, None] = '9a0cc07bc832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'part_of_speech', ['id'])
    op.create_unique_constraint(None, 'part_of_speech_words', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'part_of_speech_words', type_='unique')
    op.drop_constraint(None, 'part_of_speech', type_='unique')
    # ### end Alembic commands ###
