"""Updated Item table

Revision ID: 847158b9e7cd
Revises: 4b973c40c22f
Create Date: 2024-05-02 13:22:27.803948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '847158b9e7cd'
down_revision: Union[str, None] = '4b973c40c22f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'item', ['name'])
    op.create_unique_constraint(None, 'item', ['id'])
    op.create_unique_constraint(None, 'lesson', ['id'])
    op.create_unique_constraint(None, 'lesson_type', ['id'])
    op.create_unique_constraint(None, 'stats', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stats', type_='unique')
    op.drop_constraint(None, 'lesson_type', type_='unique')
    op.drop_constraint(None, 'lesson', type_='unique')
    op.drop_constraint(None, 'item', type_='unique')
    op.drop_constraint(None, 'item', type_='unique')
    # ### end Alembic commands ###
