"""Create part of speech for russian lng tables

Revision ID: 9a0cc07bc832
Revises: 8196df2e7398
Create Date: 2024-03-05 21:52:37.383024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a0cc07bc832'
down_revision: Union[str, None] = '8196df2e7398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('part_of_speech',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('part', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('part')
    )
    op.create_table('part_of_speech_words',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('word', sa.VARCHAR(length=100), nullable=False),
    sa.Column('part_of_speech_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['part_of_speech_id'], ['part_of_speech.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('word')
    )
    op.create_unique_constraint(None, 'classroom', ['id'])
    op.create_unique_constraint(None, 'country', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'country', type_='unique')
    op.drop_constraint(None, 'classroom', type_='unique')
    op.drop_table('part_of_speech_words')
    op.drop_table('part_of_speech')
    # ### end Alembic commands ###
