"""Removed profile picture column from profile table

Revision ID: aeefef5b3e1a
Revises: b3f245c03554
Create Date: 2024-04-20 17:45:35.691880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeefef5b3e1a'
down_revision: Union[str, None] = 'b3f245c03554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'file_accounting', ['id'])
    op.create_unique_constraint(None, 'file_type', ['id'])
    op.drop_column('profile', 'profile_picture')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('profile_picture', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'file_type', type_='unique')
    op.drop_constraint(None, 'file_accounting', type_='unique')
    # ### end Alembic commands ###
