"""Updated some tables. Added unique parametr

Revision ID: f50b9bcf6db8
Revises: 847158b9e7cd
Create Date: 2024-05-02 15:14:03.979705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f50b9bcf6db8'
down_revision: Union[str, None] = '847158b9e7cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'file_type', ['type'])
    op.create_unique_constraint(None, 'lesson_type', ['type'])
    op.create_unique_constraint(None, 'role', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'lesson_type', type_='unique')
    op.drop_constraint(None, 'file_type', type_='unique')
    # ### end Alembic commands ###
