"""Added role column in user table

Revision ID: fdc2192c54a2
Revises: 015348df9fd4
Create Date: 2024-04-28 00:51:28.579564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc2192c54a2'
down_revision: Union[str, None] = '015348df9fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'role', ['id'])
    op.add_column('user', sa.Column('role', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_constraint(None, 'role', type_='unique')
    # ### end Alembic commands ###
